services:

  debian:
    build: .
    networks:
      - sys
    depends_on: 
      - vault
    environment:
      VAULT_IP: "vault"
    tty: true

  vault:
    image: vault:1.13.3
    networks:
      - sys
    expose:
        - 8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "dev-only-token"
    cap_add:
      - IPC_LOCK

networks:
  sys:
    driver: bridge

volumes:
  users_data:
